# Generated by Django 5.1.1 on 2024-10-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_features',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
