# Generated by Django 5.1.1 on 2024-10-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('black', 'Black'), ('white', 'White'), ('green', 'Green'), ('pink', 'Pink')], default='black', max_length=10),
        ),
    ]
