# Generated by Django 5.1.1 on 2024-10-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cpu_speed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
